version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     requires:
      #       - build

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/SimpleApplicationVB2
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  # deploy:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   steps:
  #     - run:
  #         name: deploy-application
  #         command: ssh -o StrictHostKeyChecking=no $EC2_DEVOPS_VB2@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf SimpleApplicationVB2/;git clone https://github.com/DevOps-CA-1-2023/SimpleApplicationVB2.git; source SimpleApplicationVB2/deploy.sh"
